<Project Sdk="Microsoft.NET.Sdk">

  <!-- Build config -->
  <PropertyGroup>
    <AssemblyName>PowerDns.Client.UnitTests</AssemblyName>
    <RootNamespace>PowerDns.Client</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <TargetFramework>netcoreapp8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>False</IsPackable>
    <DeterministicSourcePaths>False</DeterministicSourcePaths>
    <UseMicrosoftTestingPlatformRunner>True</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --report-xunit-trx --results-directory $(MSBuildProjectDirectory)/TestResults</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <!-- Dependencies -->
  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="RichardSzalay.MockHttp" Version="7.1.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <!-- Mark as unit test project -->
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
